version: 2.1

orbs:
  flutter: circleci/flutter@1.0

jobs:
  build:
    executor: flutter/default

    steps:
      - checkout

      # Analyze Dart code using flutter analyze
      - run:
          name: Run Dart static analysis
          command: flutter analyze

      # Run tests
      - run:
          name: Run unit tests
          command: flutter test

workflows:
  version: 2
  build:
    jobs:
      - build
